Repository vindecodex/hacktoberfest-OOP, pull requests merged in 2022-10, with the labels that each got.

#4 Fix tabulations
  README.md
  base/shape.spec.ts
  base/shape.ts
  package.json
  sub-class/shape/square.spec.ts
  sub-class/shape/square.ts
  tsconfig.json
Labels: enhancement, hacktoberfest-accepted

#5 Add links and contributors profile
  README.md
Labels: enhancement, hacktoberfest-accepted

#7 Arrange folder structure
  base/shape/shape.spec.ts
  base/shape/shape.ts
  package.json
  sub-class/shape/square/square.spec.ts
  sub-class/shape/square/square.ts
Labels: enhancement, hacktoberfest-accepted

#8 Add circle subclass
  base/shape/shape.ts
  sub-class/shape/circle/circle.spec.ts
  sub-class/shape/circle/circle.ts
Labels: enhancement, hacktoberfest-accepted

#9 Add new base class car
  base/car/car.spec.ts
  base/car/car.ts
Labels: hacktoberfest-accepted

#10 Add triangle subclass
  sub-class/shape/triangle/triangle.spec.ts
  sub-class/shape/triangle/triangle.ts
  tsconfig.json
Labels: enhancement, hacktoberfest-accepted

#12 Added subclass toyota
  sub-class/car/toyota/toyota.spec.ts
  sub-class/car/toyota/toyota.ts
Labels: hacktoberfest-accepted

#13 Sub-class: Added Tesla
  sub-class/car/tesla/tesla.spec.ts
  sub-class/car/tesla/tesla.ts
Labels: hacktoberfest-accepted

#15 Add subclass Mitsubishi
  sub-class/car/mitsubishi.spec.ts
  sub-class/car/mitsubishi.ts
Labels: hacktoberfest-accepted

#14 Add subclass Honda
  sub-class/car/honda.spec.ts
  sub-class/car/honda.ts
Labels: hacktoberfest-accepted

#17 add subclass 'Mazda'
  sub-class/car/mazda/mazda.spec.ts
  sub-class/car/mazda/mazda.ts
Labels: hacktoberfest-accepted

#16 add subclass 'Nissan'
  sub-class/car/nissan/nissan.spec.ts
  sub-class/car/nissan/nissan.ts
Labels: good first issue, hacktoberfest-accepted
